export const POA_CHECK = {
	ADDRESS_EMPTY: '@error/poa/CHECK/ADDRESS_EMPTY',
	ADDRESS_INVALID_LENGTH: '@error/poa/CHECK/ADDRESS_INVALID_LENGTH'
};

export const POA_NOMINATE = {
	ADDRESS_EMPTY: '@error/poa/NOMINATE/ADDRESS_EMPTY',
	ADDRESS_INVALID_LENGTH: '@error/poa/NOMINATE/ADDRESS_INVALID_LENGTH',
	MONIKER_EMPTY: '@error/poa/NOMINATE/MONIKER_EMPTY',

	FROM_EMPTY: '@error/poa/NOMINATE/FROM_EMPTY',
	FROM_INVALID_LENGTH: '@error/poa/NOMINATE/FROM_INVALID_LENGTH',

	PWD_PATH_EMPTY: '@error/poa/NOMINATE/PWD_PATH_EMPTY',
	PWD_IS_DIR: '@error/poa/NOMINATE/PWD_IS_DIR',
	PWD_PATH_NOT_FOUND: '@error/poa/NOMINATE/PWD_PATH_NOT_FOUND'
};

export const POA_VOTE = {
	ADDRESS_EMPTY: '@error/poa/VOTE/ADDRESS_EMPTY',
	ADDRESS_INVALID_LENGTH: '@error/poa/VOTE/ADDRESS_INVALID_LENGTH',

	FROM_EMPTY: '@error/poa/VOTE/FROM_EMPTY',
	FROM_INVALID_LENGTH: '@error/poa/VOTE/FROM_INVALID_LENGTH',

	VERDICT_EMPTY: '@error/poa/VOTE/VERDICT_EMPTY',

	PWD_PATH_EMPTY: '@error/poa/VOTE/PWD_PATH_EMPTY',
	PWD_IS_DIR: '@error/poa/VOTE/PWD_IS_DIR',
	PWD_PATH_NOT_FOUND: '@error/poa/VOTE/PWD_PATH_NOT_FOUND',

	NO_NOMINEES: '@error/poa/VOTE/NO_NOMINEES'
};

export const POA_INIT = {
	ADDRESS_EMPTY: '@error/poa/INIT/ADDRESS_EMPTY',
	ADDRESS_INVALID_LENGTH: '@error/poa/INIT/ADDRESS_INVALID_LENGTH',

	PWD_PATH_EMPTY: '@error/poa/INIT/PWD_PATH_EMPTY',
	PWD_IS_DIR: '@error/poa/INIT/PWD_IS_DIR',
	PWD_PATH_NOT_FOUND: '@error/poa/INIT/PWD_PATH_NOT_FOUND'
};
